### ISSUE TITLE
syntax error, unexpected tLABEL 

### ISSUE THREAD

**Issue by joe-bowman** [bundler/gemstash#105]
Hi, I'm installing gemstash on a fresh ubuntu 14.04 vagrant box as per the README.md, and getting a syntax error. I'm not particularly familiar with ruby, so would be grateful for any pointers.

Thanks,

Joe

```
vagrant@gemstash-01:~$ sudo apt-get install ruby ruby-dev libsqlite3-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
ruby is already the newest version.
ruby-dev is already the newest version.
Suggested packages:
  sqlite3-doc
The following NEW packages will be installed:
  libsqlite3-dev
0 upgraded, 1 newly installed, 0 to remove and 10 not upgraded.
Need to get 439 kB of archives.
After this operation, 1,491 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://uk.archive.ubuntu.com/ubuntu/ trusty-updates/main libsqlite3-dev amd64 3.8.2-1ubuntu2.1 [439 kB]
Fetched 439 kB in 0s (2,137 kB/s)
Selecting previously unselected package libsqlite3-dev:amd64.
(Reading database ... 73881 files and directories currently installed.)
Preparing to unpack .../libsqlite3-dev_3.8.2-1ubuntu2.1_amd64.deb ...
Unpacking libsqlite3-dev:amd64 (3.8.2-1ubuntu2.1) ...
Setting up libsqlite3-dev:amd64 (3.8.2-1ubuntu2.1) ...
vagrant@gemstash-01:~$ sudo gem install gemstash
Fetching: dalli-2.7.6.gem (100%)
Fetching: lru_redux-1.1.0.gem (100%)
Fetching: puma-2.16.0.gem (100%)
Building native extensions.  This could take a while...
Fetching: sequel-4.38.0.gem (100%)
Fetching: rack-1.6.4.gem (100%)
Fetching: tilt-2.0.5.gem (100%)
Fetching: rack-protection-1.5.3.gem (100%)
Fetching: sinatra-1.4.7.gem (100%)
Fetching: thor-0.19.1.gem (100%)
Fetching: multipart-post-2.0.0.gem (100%)
Fetching: faraday-0.9.2.gem (100%)
Fetching: faraday_middleware-0.10.0.gem (100%)
Fetching: sqlite3-1.3.11.gem (100%)
Building native extensions.  This could take a while...
Fetching: gemstash-1.0.2.gem (100%)
Successfully installed dalli-2.7.6
Successfully installed lru_redux-1.1.0
Successfully installed puma-2.16.0
Successfully installed sequel-4.38.0
Successfully installed rack-1.6.4
Successfully installed tilt-2.0.5
Successfully installed rack-protection-1.5.3
Successfully installed sinatra-1.4.7
Successfully installed thor-0.19.1
Successfully installed multipart-post-2.0.0
Successfully installed faraday-0.9.2
Successfully installed faraday_middleware-0.10.0
Successfully installed sqlite3-1.3.11
Successfully installed gemstash-1.0.2
14 gems installed
Installing ri documentation for dalli-2.7.6...
Installing ri documentation for lru_redux-1.1.0...
Installing ri documentation for puma-2.16.0...
Installing ri documentation for sequel-4.38.0...
Installing ri documentation for rack-1.6.4...
Installing ri documentation for tilt-2.0.5...
Installing ri documentation for rack-protection-1.5.3...
Installing ri documentation for sinatra-1.4.7...
Installing ri documentation for thor-0.19.1...
Installing ri documentation for multipart-post-2.0.0...
Installing ri documentation for faraday-0.9.2...
Installing ri documentation for faraday_middleware-0.10.0...
Installing ri documentation for sqlite3-1.3.11...
Installing ri documentation for gemstash-1.0.2...
Installing RDoc documentation for dalli-2.7.6...
Installing RDoc documentation for lru_redux-1.1.0...
Installing RDoc documentation for puma-2.16.0...
Installing RDoc documentation for sequel-4.38.0...
Installing RDoc documentation for rack-1.6.4...
Installing RDoc documentation for tilt-2.0.5...
Installing RDoc documentation for rack-protection-1.5.3...
Installing RDoc documentation for sinatra-1.4.7...
Installing RDoc documentation for thor-0.19.1...
Installing RDoc documentation for multipart-post-2.0.0...
Installing RDoc documentation for faraday-0.9.2...
Installing RDoc documentation for faraday_middleware-0.10.0...
Installing RDoc documentation for sqlite3-1.3.11...
Installing RDoc documentation for gemstash-1.0.2...
vagrant@gemstash-01:~$ gemstash start
/var/lib/gems/1.9.1/gems/gemstash-1.0.2/lib/gemstash/cli/base.rb:7:in `<class:Base>': /var/lib/gems/1.9.1/gems/gemstash-1.0.2/lib/gemstash/env.rb:37: syntax error, unexpected tLABEL (SyntaxError)
    def initialize(config = nil, cache: nil, db: nil)
                                       ^
/var/lib/gems/1.9.1/gems/gemstash-1.0.2/lib/gemstash/env.rb:37: Can't assign to nil
    def initialize(config = nil, cache: nil, db: nil)
                                            ^
/var/lib/gems/1.9.1/gems/gemstash-1.0.2/lib/gemstash/env.rb:150: syntax error, unexpected keyword_end, expecting $end
       	from /var/lib/gems/1.9.1/gems/gemstash-1.0.2/lib/gemstash/cli/base.rb:6:in `<class:CLI>'
       	from /var/lib/gems/1.9.1/gems/gemstash-1.0.2/lib/gemstash/cli/base.rb:4:in `<module:Gemstash>'
       	from /var/lib/gems/1.9.1/gems/gemstash-1.0.2/lib/gemstash/cli/base.rb:3:in `<top (required)>'
       	from /var/lib/gems/1.9.1/gems/gemstash-1.0.2/lib/gemstash/cli/start.rb:8:in `<class:CLI>'
       	from /var/lib/gems/1.9.1/gems/gemstash-1.0.2/lib/gemstash/cli/start.rb:5:in `<module:Gemstash>'
       	from /var/lib/gems/1.9.1/gems/gemstash-1.0.2/lib/gemstash/cli/start.rb:4:in `<top (required)>'
       	from /var/lib/gems/1.9.1/gems/gemstash-1.0.2/lib/gemstash/cli.rb:54:in `start'
       	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
       	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
       	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
       	from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
       	from /var/lib/gems/1.9.1/gems/gemstash-1.0.2/exe/gemstash:3:in `<top (required)>'
       	from /usr/local/bin/gemstash:23:in `load'
       	from /usr/local/bin/gemstash:23:in `<main>'
```

**Comment by pcarranza** [comment]
It looks like your ruby version is too old. Check rbenv r similar to bump
at least to ruby 2.something.

I think that the minimum supported ruby was 1.9.3 and yours looks like
1.9.1.

Hence its incompatible.

**Comment by pcarranza** [comment]
I'm closing this as there is no action forward. Please update your Ruby.
