### ISSUE TITLE
Ugly trace vomited to bundler when upstream connection fails while resolving dependencies

### ISSUE THREAD

**Issue by pcarranza** [bundler/gemstash#27]
Nothing to worry about, seems to be an edge case, but it outputted a lot of data that didn't make any sense.

Probably we need to guard ourselves from failing connections.

```
[2015-10-13 15:36:10 -0400] - INFO - Fetching dependencies: netrc, mime-types, http-cookie, rdoc, simplecov-html, docile, lockfile, power_assert, ast, slop, sexp_processor, little-plugger, loquacious, bones-git, bones-extras, abstract, metaclass, needle, jruby-pageant, echoe, arel, activemodel, tzinfo, activerecord-deprecated_finders, thread_safe, minitest
[2015-10-13 15:36:15 -0400] - ERROR - 2015-10-13 15:36:15 - Faraday::ConnectionFailed - execution expired:
	/home/pcarranza/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
	/home/pcarranza/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:879:in `open'
	/home/pcarranza/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:879:in `block in connect'
	/home/pcarranza/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:89:in `block in timeout'
	/home/pcarranza/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `call'
	/home/pcarranza/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:99:in `timeout'
	/home/pcarranza/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:878:in `connect'
	/home/pcarranza/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
	/home/pcarranza/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:852:in `start'
	/home/pcarranza/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1375:in `request'
	/home/pcarranza/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:1133:in `get'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:80:in `perform_request'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:40:in `block in call'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.1/lib/faraday/adapter/net_http.rb:32:in `call'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:76:in `perform_with_redirection'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/faraday_middleware-0.10.0/lib/faraday_middleware/response/follow_redirects.rb:64:in `call'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/faraday-0.9.1/lib/faraday/connection.rb:140:in `get'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/gemstash-0.1.0/lib/gemstash/http_client.rb:37:in `get'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/gemstash-0.1.0/lib/gemstash/dependencies.rb:77:in `fetch_from_web'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/gemstash-0.1.0/lib/gemstash/dependencies.rb:42:in `fetch'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/gemstash-0.1.0/lib/gemstash/dependencies.rb:23:in `fetch'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/gemstash-0.1.0/lib/gemstash/gem_source/dependency_caching.rb:15:in `serve_dependencies'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/gemstash-0.1.0/lib/gemstash/web.rb:34:in `block in <class:Web>'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `call'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1610:in `block in compile!'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `[]'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (3 levels) in route!'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:993:in `route_eval'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:974:in `block (2 levels) in route!'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1014:in `block in process_route'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `catch'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1012:in `process_route'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:972:in `block in route!'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `each'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:971:in `route!'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1084:in `block in dispatch!'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1081:in `dispatch!'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `block in call!'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `block in invoke'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `catch'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:1066:in `invoke'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:906:in `call!'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:894:in `call'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/rack-1.4.5/lib/rack/nulllogger.rb:9:in `call'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/rack-1.4.5/lib/rack/head.rb:9:in `call'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/show_exceptions.rb:21:in `call'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:181:in `call'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/sinatra-1.4.6/lib/sinatra/base.rb:2021:in `call'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/gemstash-0.1.0/lib/gemstash/gem_source/rack_middleware.rb:18:in `call'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/gemstash-0.1.0/lib/gemstash/env.rb:32:in `call'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/puma-2.14.0/lib/puma/commonlogger.rb:31:in `call'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/gemstash-0.1.0/lib/gemstash/logging.rb:42:in `call'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/rack-1.4.5/lib/rack/deflater.rb:13:in `call'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/puma-2.14.0/lib/puma/configuration.rb:78:in `call'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/puma-2.14.0/lib/puma/server.rb:541:in `handle_request'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/puma-2.14.0/lib/puma/server.rb:388:in `process_client'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/puma-2.14.0/lib/puma/server.rb:270:in `block in run'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/puma-2.14.0/lib/puma/thread_pool.rb:106:in `call'
	/home/pcarranza/.rvm/gems/ruby-2.2.1/gems/puma-2.14.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

**Comment by pcarranza** [comment]
Done done done
