### ISSUE TITLE
Errors trying to bundle

### ISSUE THREAD

**Issue by smellsblue** [bundler/gemstash#83]
I just installed gemstash and got the following errors trying to bundle:

```
$ bundle
Fetching gem metadata from http://localhost:9292/...........
Fetching version metadata from http://localhost:9292/..
Resolving dependencies...
Installing rake 10.5.0
Installing diff-lcs 1.2.5
Using thor 0.19.1
Installing rspec-support 3.4.1
Using bundler 1.11.2
Using nginxtra 1.8.0.11 from source at `.`

Gem::RemoteFetcher::FetchError: bad response Internal Server Error 500 (http://localhost:9292/gems/rspec-core-3.4.4.gem)

Gem::RemoteFetcher::FetchError: bad response Internal Server Error 500 (http://localhost:9292/gems/rspec-expectations-3.4.0.gem)

Gem::RemoteFetcher::FetchError: bad response Internal Server Error 500 (http://localhost:9292/gems/rspec-mocks-3.4.1.gem)
An error occurred while installing rspec-core (3.4.4), and Bundler cannot continue.
Make sure that `gem install rspec-core -v '3.4.4'` succeeds before bundling.
```

I looked into the log:
```
[2016-03-20 17:08:23 -0700] - INFO - Gem rspec-core-3.4.4 exists, returning cached gem
[2016-03-20 17:08:23 -0700] - INFO - 127.0.0.1 - - [20/Mar/2016:17:08:23 -0700] "GET /gems/rspec-core-3.4.4.gem HTTP/1.1" 200 145920 0.0060
[2016-03-20 17:08:23 -0700] - INFO - Gem rspec-expectations-3.4.0 exists, returning cached gem
[2016-03-20 17:08:23 -0700] - INFO - 127.0.0.1 - - [20/Mar/2016:17:08:23 -0700] "GET /gems/rspec-expectations-3.4.0.gem HTTP/1.1" 200 75264 0.0041
[2016-03-20 17:08:23 -0700] - INFO - Gem rspec-mocks-3.4.1 exists, returning cached gem
[2016-03-20 17:08:23 -0700] - INFO - 127.0.0.1 - - [20/Mar/2016:17:08:23 -0700] "GET /gems/rspec-mocks-3.4.1.gem HTTP/1.1" 200 74752 0.0030
[2016-03-20 17:08:24 -0700] - INFO - Gem rspec-3.4.0 is not cached, fetching gem
[2016-03-20 17:08:24 -0700] - ERROR - 2016-03-20 17:08:24 - Sequel::DatabaseError - SQLite3::SQLException: no such table: upstreams:
	~/.rvm/gems/ruby-2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `initialize'
	~/.rvm/gems/ruby-2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `new'
	~/.rvm/gems/ruby-2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:91:in `prepare'
	~/.rvm/gems/ruby-2.3.0/gems/sqlite3-1.3.11/lib/sqlite3/database.rb:266:in `query'
	~/.rvm/gems/ruby-2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/sqlite.rb:187:in `block (2 levels) in _execute'
	~/.rvm/gems/ruby-2.3.0/gems/sequel-4.32.0/lib/sequel/database/logging.rb:35:in `log_yield'
	~/.rvm/gems/ruby-2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/sqlite.rb:187:in `block in _execute'
	~/.rvm/gems/ruby-2.3.0/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:251:in `block in synchronize'
	~/.rvm/gems/ruby-2.3.0/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:101:in `hold'
	~/.rvm/gems/ruby-2.3.0/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:251:in `synchronize'
	~/.rvm/gems/ruby-2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/sqlite.rb:180:in `_execute'
	~/.rvm/gems/ruby-2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/sqlite.rb:130:in `execute'
	~/.rvm/gems/ruby-2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/actions.rb:952:in `execute'
	~/.rvm/gems/ruby-2.3.0/gems/sequel-4.32.0/lib/sequel/adapters/sqlite.rb:322:in `fetch_rows'
	~/.rvm/gems/ruby-2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/actions.rb:833:in `with_sql_each'
	~/.rvm/gems/ruby-2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/actions.rb:843:in `with_sql_first'
	~/.rvm/gems/ruby-2.3.0/gems/sequel-4.32.0/lib/sequel/dataset/placeholder_literalizer.rb:150:in `first'
	~/.rvm/gems/ruby-2.3.0/gems/sequel-4.32.0/lib/sequel/model/base.rb:878:in `block in def_finder_method'
	~/.rvm/gems/ruby-2.3.0/gems/sequel-4.32.0/lib/sequel/model/base.rb:112:in `[]'
	~/.rvm/gems/ruby-2.3.0/gems/gemstash-1.0.1/lib/gemstash/db/upstream.rb:6:in `find_or_insert'
	~/.rvm/gems/ruby-2.3.0/gems/gemstash-1.0.1/lib/gemstash/db/cached_rubygem.rb:9:in `block in store'
	~/.rvm/gems/ruby-2.3.0/gems/sequel-4.32.0/lib/sequel/database/transactions.rb:136:in `_transaction'
	~/.rvm/gems/ruby-2.3.0/gems/sequel-4.32.0/lib/sequel/database/transactions.rb:110:in `block in transaction'
	~/.rvm/gems/ruby-2.3.0/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:251:in `block in synchronize'
	~/.rvm/gems/ruby-2.3.0/gems/sequel-4.32.0/lib/sequel/connection_pool/threaded.rb:105:in `hold'
	~/.rvm/gems/ruby-2.3.0/gems/sequel-4.32.0/lib/sequel/database/connecting.rb:251:in `synchronize'
	~/.rvm/gems/ruby-2.3.0/gems/sequel-4.32.0/lib/sequel/database/transactions.rb:99:in `transaction'
	~/.rvm/gems/ruby-2.3.0/gems/gemstash-1.0.1/lib/gemstash/db/cached_rubygem.rb:8:in `store'
	~/.rvm/gems/ruby-2.3.0/gems/gemstash-1.0.1/lib/gemstash/gem_source/upstream_source.rb:178:in `block in fetch_remote_gem'
	~/.rvm/gems/ruby-2.3.0/gems/gemstash-1.0.1/lib/gemstash/gem_fetcher.rb:16:in `block in fetch'
	~/.rvm/gems/ruby-2.3.0/gems/gemstash-1.0.1/lib/gemstash/http_client.rb:56:in `get'
	~/.rvm/gems/ruby-2.3.0/gems/gemstash-1.0.1/lib/gemstash/gem_fetcher.rb:13:in `fetch'
	~/.rvm/gems/ruby-2.3.0/gems/gemstash-1.0.1/lib/gemstash/gem_source/upstream_source.rb:170:in `fetch_remote_gem'
	~/.rvm/gems/ruby-2.3.0/gems/gemstash-1.0.1/lib/gemstash/gem_source/upstream_source.rb:159:in `fetch_gem'
	~/.rvm/gems/ruby-2.3.0/gems/gemstash-1.0.1/lib/gemstash/gem_source/upstream_source.rb:122:in `serve_cached'
	~/.rvm/gems/ruby-2.3.0/gems/gemstash-1.0.1/lib/gemstash/gem_source/upstream_source.rb:116:in `serve_gem'
	~/.rvm/gems/ruby-2.3.0/gems/gemstash-1.0.1/lib/gemstash/web.rb:82:in `block in <class:Web>'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `call'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1611:in `block in compile!'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
	~/.rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	~/.rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	~/.rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	~/.rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	~/.rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	~/.rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	~/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
	~/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb:25:in `call'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
	~/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
	~/.rvm/gems/ruby-2.3.0/gems/gemstash-1.0.1/lib/gemstash/gem_source/rack_middleware.rb:18:in `call'
	~/.rvm/gems/ruby-2.3.0/gems/gemstash-1.0.1/lib/gemstash/env.rb:33:in `call'
	~/.rvm/gems/ruby-2.3.0/gems/puma-2.16.0/lib/puma/commonlogger.rb:31:in `call'
	~/.rvm/gems/ruby-2.3.0/gems/gemstash-1.0.1/lib/gemstash/logging.rb:56:in `call'
	~/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/deflater.rb:35:in `call'
	~/.rvm/gems/ruby-2.3.0/gems/puma-2.16.0/lib/puma/configuration.rb:81:in `call'
	~/.rvm/gems/ruby-2.3.0/gems/puma-2.16.0/lib/puma/server.rb:557:in `handle_request'
	~/.rvm/gems/ruby-2.3.0/gems/puma-2.16.0/lib/puma/server.rb:404:in `process_client'
	~/.rvm/gems/ruby-2.3.0/gems/puma-2.16.0/lib/puma/server.rb:270:in `block in run'
	~/.rvm/gems/ruby-2.3.0/gems/puma-2.16.0/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

Here's my installed gems:
```
$ gem list

*** LOCAL GEMS ***

bigdecimal (1.2.8)
bundler (1.11.2)
bundler-unload (1.0.2)
dalli (2.7.6)
did_you_mean (1.0.0)
diff-lcs (1.2.5)
executable-hooks (1.3.2)
faraday (0.9.2)
faraday_middleware (0.10.0)
gem-wrappers (1.2.7)
gemstash (1.0.1)
io-console (0.4.5)
json (1.8.3)
lru_redux (1.1.0)
minitest (5.8.3)
multipart-post (2.0.0)
net-telnet (0.1.1)
power_assert (0.2.6)
psych (2.0.17)
puma (2.16.0)
rack (1.6.4)
rack-protection (1.5.3)
rake (10.5.0, 10.4.2)
rdoc (4.2.1)
rspec (3.4.0)
rspec-core (3.4.4)
rspec-expectations (3.4.0)
rspec-mocks (3.4.1)
rspec-support (3.4.1)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
sequel (4.32.0)
sinatra (1.4.7)
sqlite3 (1.3.11)
test-unit (3.1.5)
thor (0.19.1)
tilt (2.0.2)
```

Here is the gemfile.lock I was bundling with:
```
PATH
  remote: .
  specs:
    nginxtra (1.8.0.11)
      thor (~> 0.16)

GEM
  remote: https://rubygems.org/
  specs:
    diff-lcs (1.2.5)
    rake (10.5.0)
    rspec (3.4.0)
      rspec-core (~> 3.4.0)
      rspec-expectations (~> 3.4.0)
      rspec-mocks (~> 3.4.0)
    rspec-core (3.4.4)
      rspec-support (~> 3.4.0)
    rspec-expectations (3.4.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.4.0)
    rspec-mocks (3.4.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.4.0)
    rspec-support (3.4.1)
    thor (0.19.1)

PLATFORMS
  ruby

DEPENDENCIES
  nginxtra!
  rake (~> 10.0)
  rspec (~> 3.3)

BUNDLED WITH
   1.11.2
```

My first inclination is our loose dependencies might be biting us again, but I'm not really sure yet.

**Comment by pcarranza** [comment]
It's weird, it complains that a table does not exists.

Does this reproduce every time you do the same thing? if so, why does the DB fails? could we short circuit the DB to avoid hard failing on it?

**Comment by smellsblue** [comment]
@pcarranza I was working on another project and didn't really want to switch contexts, so I haven't had a chance to debug it... however what seemed to be happening... it would fail the first time trying to install a gem, then successfully install it on the next attempt. Then it would repeat for the dependencies... so depending on how deep the dependencies tree is, I could bundle like 3 times and it would work. As long as Gemstash didn't have the gem cached, it seems like it predictably fails every time.

**Comment by pcarranza** [comment]
Could you try cleaning your environment?

I still find really weird that the exception is `SQLite3::SQLException: no such table: upstreams:`

**Comment by smellsblue** [comment]
I tried this again and it happened again... so I deleted my `~/.gemstash` directory and it started working. I'm going to go out on a limb and say this is probably just a stale directory left over from earlier development of Gemstash. I haven't seen any other reports of this, so I'm closing this.
